[package]
name = "prost-reflect"
description = "A protobuf library extending prost with reflection support and dynamic messages."
keywords = ["protobuf", "serialization", "json"]
categories = ["encoding"]
version = "0.8.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/prost-reflect"
documentation = "https://docs.rs/prost-reflect"
license = "MIT OR Apache-2.0"
readme = "../README.md"
edition = "2018"
rust-version = "1.54.0"
exclude = ["proptest-regressions", "src/file_descriptor_set.bin"]
build = "build.rs"

[features]
derive = ["prost-reflect-derive"]
serde = ["serde1", "base64", "serde-value"]
reflect-well-known-types = ["once_cell", "prost-build"]

[dependencies]
base64 = { version = "0.13.0", optional = true }
once_cell = { version = "1.9.0", optional = true }
prost = { git = "https://github.com/tokio-rs/prost", branch = "master" }
prost-reflect-derive = { path = '../prost-reflect-derive', version = "0.8.0", optional = true }
prost-types = { git = "https://github.com/tokio-rs/prost", branch = "master" }
serde-value = { version = "0.7.0", optional = true }
serde1 = { package = "serde", version = "1.0.132", optional = true }

[dev-dependencies]
once_cell = "1.9.0"
proptest = "1.0.0"
prost-build = { git = "https://github.com/tokio-rs/prost", branch = "master" }
prost-reflect-build = { path = "../prost-reflect-build" }
serde_json = "1.0.73"

[build-dependencies]
prost-build = { git = "https://github.com/tokio-rs/prost", branch = "master", optional = true }

[package.metadata.release]
tag-name = "{{version}}"
sign-tag = true

[[package.metadata.release.pre-release-replacements]]
file = "../README.md"
search = "https://deps\\.rs/crate/prost-reflect/.*?/status.svg"
replace = "https://deps.rs/crate/prost-reflect/{{version}}/status.svg"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "../README.tpl"
search = "https://deps\\.rs/crate/prost-reflect/.*?/status.svg"
replace = "https://deps.rs/crate/prost-reflect/{{version}}/status.svg"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "../README.md"
search = "https://docs\\.rs/prost-reflect/.*?/prost_reflect"
replace = "https://docs.rs/prost-reflect/{{version}}/prost_reflect"
min = 1

[[package.metadata.release.pre-release-replacements]]
file = "../README.tpl"
search = "https://docs\\.rs/prost-reflect/.*?/prost_reflect"
replace = "https://docs.rs/prost-reflect/{{version}}/prost_reflect"
min = 1

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "html_root_url = \"https://docs.rs/prost-reflect/.*?/\""
replace = "html_root_url = \"https://docs.rs/prost-reflect/{{version}}/\""
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "../CHANGELOG.md"
search = "## \\[Unreleased\\]"
replace = "## [Unreleased]\n\n## [{{version}}] - {{date}}"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "../CHANGELOG.md"
search = "\\[Unreleased\\]: https://github\\.com/andrewhickman/prost-reflect/compare/.*?...HEAD"
replace = "[Unreleased]: https://github.com/andrewhickman/prost-reflect/compare/{{version}}...HEAD\n[{{version}}]: https://github.com/andrewhickman/prost-reflect/compare/{{prev_version}}...{{version}}"
exactly = 1

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
