[package]
name = "prost-reflect-derive"
description = "A derive macro for prost-reflect to generate ReflectMessage implementations"
keywords = ["protobuf", "serialization", "json"]
categories = ["encoding"]
version = "0.8.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/prost-reflect"
documentation = "https://docs.rs/prost-reflect-derive"
license = "MIT OR Apache-2.0"
readme = "../README.md"
edition = "2018"
rust-version = "1.54.0"
autotests = false
exclude = ["tests"]

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.14"
syn = "1.0.84"

[dev-dependencies]
once_cell = "1.9.0"
prost = { git = "https://github.com/andrewhickman/prost", branch = "master" }
prost-reflect = { path = "../prost-reflect", features = ["derive"] }
trybuild = "1.0.53"

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "html_root_url = \"https://docs.rs/prost-reflect-derive/.*?/\""
replace = "html_root_url = \"https://docs.rs/prost-reflect-derive/{{version}}/\""
exactly = 1

[package.metadata.release]
tag = false
